name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install packages
        run: npm ci

      - name: Verify code formatting
        run: npm run prettier:verify

      - name: Lint Code
        run: npm run lint

      - name: Build app
        run: npm build

      - name: Run tests
        run: npm run test:ci

  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
